name: Run main.py

on:
  schedule:
    - cron: '30 10 * * *' # Runs at 6:30 AM EST (10:30 UTC) every day
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.3' # Replace x with your desired Python version
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: execute main.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python main.py
